# Generated by Django 3.0.3 on 2020-02-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_changed_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.TextField(default='https://www.netclipart.com/pp/m/23-234697_blue-onesie-clipart-stick-figure-happy-face.png'),
            preserve_default=False,
        ),
    ]
