language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
- SECRET=test-key DBNAME=travis_ci_test
script:
- python manage.py test notary_now_api
deploy:
  provider: heroku
  api_key:
    secure: H2rjrHsO3zPPxWdJ5r/kjM00vnbfI+4BToEQYQgeyZzKd5fzY8zkTVZMBOdyD3zN1Nr4cBAMY/wm5WYsdikHMQat47xQR2xXqYqY32hYL/YRu/IvQwAcUCVYKrESMbraIehzlvnJjYAB1vRH9XHdfZVDSFiIAZPlCHF5tYXWGBiOMBpyDOOCd0RFUEu8ZcSWMSILrPKYxr6F0MvgCSXSlE2BujG1KFh9WC6UbnMSGikdSM77SWEcI9doQjdd4RCkEEZA8MeRAREuYX2trW1lzlT1V2wwNmYoaVldEGHO82wwN2ZdmOnK++BYrB8v5LZT6neQkOdMqDeeJJqkZ7opYrxugLlKe4UOM+BPDeLQr+q4PJG1MwQrlplH47nQt5Icyuk/2LKS3SRlV4Dp8pZpUfQSCl5fdD57kgrv653Hhocj38BZIHt+QIjSqUsQZjSa0ExvlUhJ7yD8b58wZHtEoOTxRzCTPwoHsXQF76j1IAItsPE5tGINp+IIDsEFDFAUfFhxoyJlsOptwt4h3JnK7xy6YmwyICP4k0ex1YXl+0zP/1fPIbLOeLXyQ+yhk4w6dFfMtXR+PDz6dfjLkwbaZ0E/5honLFbntmgQqhb/T+U1DsPGCCMnL/11jG95PE4ZiYyI1yTekXXpB83MfL15Bzpdq/k5ug3/WB/bpCIxcRE=
  app: backend-notary-now
  on:
    repo: notary-now/backend_notary_now
