# Generated by Django 3.0.3 on 2020-02-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notary',
            name='commission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notary',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
