# Generated by Django 3.0.3 on 2020-02-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0002_appointment_language_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apointee_id',
            new_name='apointee',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='user_id',
            new_name='user',
        ),
    ]
