# Generated by Django 3.0.3 on 2020-02-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0003_notary_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_notary',
        ),
    ]
