# Generated by Django 3.0.3 on 2020-02-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0004_remove_user_is_notary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notary',
            name='bio',
        ),
    ]
