# Generated by Django 3.0.3 on 2020-02-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0009_auto_20200220_2210'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_user_appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='apointee',
            new_name='appointee',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('date', 'time', 'appointee_id'), name='unique_user_appointment'),
        ),
    ]
