# Generated by Django 3.0.3 on 2020-02-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0010_auto_20200220_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Cancelled')], default=1),
        ),
    ]
