# Generated by Django 3.0.3 on 2020-02-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0012_auto_20200222_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
