# Generated by Django 3.0.3 on 2020-02-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0016_auto_20200225_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='a0d9ccd1c7284759a10e3779f4c5ce5c', max_length=50, unique=True),
        ),
    ]
