# Generated by Django 3.0.3 on 2020-02-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_now_api', '0017_auto_20200225_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='c5055f63cad5449e957a31909eea1410', max_length=50),
        ),
    ]
